name: Release DevOps with Docker

# On a push to the branch named master
on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Builds devopsdockeruh/docker-hy.github.io
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sokkajar/dockerpipe:latest
